version: "3"
services:
  node:
    image: node:12-alpine
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    command: npm run dev
  mongo:
    image: mongo
    volumes:
      - ./mongodata:/data/db
    env_file:
      - .env
